### PR TITLE
State machine

### PR DESCRIPTION
**Pull request by cholcombe973**
This drastically changes how test_disk functions and changes it over to using a state machine.  The code will print out a digraph when tests are run so that the logic tree can be visualized.

### CODE REVIEW

**Comment by cholcombe973** [comment]
@sdandam I'd suggest pulling this branch down to your local machine and running the tests to get a feel for what this is doing.  It also might be helpful to take the digraph and print it as a svg and check what transitions are happening.  I don't think this is perfect yet but it's working decently well at this point that I want to start the review process.

**Comment by cholcombe973** [comment]
Well this is a bummer.  I ran into a cargo bug: https://github.com/rust-lang/cargo/issues/4866 and it'll require us staying on nightly until it gets resolved.  Not sure what else we can do it about it.  I tried various things and nothing helps with getting this to compile on stable.

**Comment by jhg03a** [comment]
Awesome to see this

**Comment by cholcombe973** [comment]
No problem.  We've got a lot more testing to do before this makes it into production

**Pull request merged**
